version: "3"
services: 
    client:
        container_name: angularfrontend
        build:
            context: ./HFS-FE
            dockerfile: ./Dockerfile
        ports: 
            - 4200:4200
        #volumes:
        #    - shared:/app/dist
    nginx:
        container_name: middlenginx
        image: nginx:alpine
        #build: nginx
        #restart: always
        expose:
            - "80"
        ports: 
            - "80:80"
          #  - "433:433"
        #links:
        #    - api
        volumes:

            - ./nginx.middle.conf:/etc/nginx/conf.d/default.conf:rw
        #    - shared:/usr/share/nginx/html
        #    - ./nginx.conf:/etc/nginx/nginx.conf
            
        depends_on: 
            - api
  
    api:
        container_name: dotnetbackend
        build: 
            context: ./HFS-BE
            dockerfile: ./Dockerfile
        ports: 
            - "5000:5000"
        restart: always
        depends_on: 
            - db
        volumes:
            - image-data:/app/Resources
    db:
        #image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: mssql
        hostname: mssql
        user: root
        build: 
            context: ./Db
            dockerfile: ./Dockerfile
        #network_mode: "host"
        ports: 
            - "1450:1433"
        restart: always
        environment:
            ACCEPT_EULA: Y
            MSSQL_SA_PASSWORD: Passw0rd
            MSSQL_TCP_PORT: 1433
        volumes:
            - database-data:/var/opt/mssql
volumes:
  database-data:
  image-data:

