version: "3"
services: 
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Passw0rd"
            ACCEPT_EULA: "Y"
    api:
        build: HFS-BE/HFS-BE
        ports: 
            - 3000:80
        depends_on: 
            - db
        links:
            - db
    client:
        build: HFS-FE
        ports: 
            - 4200:80
        volumes:
            - shared:/app/dist
    nginx:
        image: nginx:1.13-alpine
        build: nginx
        restart: always
        depends_on: 
            - client
            - api
        links:
            - api
        volumes:
            - shared:/usr/share/nginx/html
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports: 
            - 80:80
volumes:
  shared: {}
networks:
    internalnet:
        driver: bridge

