version: "3"
services: 
    client:
        container_name: angularfrontend
        build:
            context: ./HFS-FE
            dockerfile: ./Dockerfile
        ports: 
            - 4200:4200
        #volumes:
        #    - shared:/app/dist
        networks:
            - internalnet
    nginx:
        container_name: middlenginx
        image: nginx:alpine
        #build: nginx
        #restart: always
        expose:
            - "80"
        ports: 
            - "80:80"
          #  - "433:433"
        #links:
        #    - api
        volumes:

            - ./nginx.middle.conf:/etc/nginx/conf.d/default.conf:rw
        #    - shared:/usr/share/nginx/html
        #    - ./nginx.conf:/etc/nginx/nginx.conf
            
        depends_on: 
            - api
        networks:
            - internalnet
    
    api:
        container_name: dotnetbackend
        build: 
            context: ./HFS-BE
            dockerfile: ./Dockerfile
        ports: 
            - "5000:5000"
        restart: always
        depends_on: 
            - db
        #links:
        #    - db
        networks:
            - internalnet 
        #environment:
            #- ConnectionStrings__DefaultConnection=mssql;database=SEP490_HFS_2;User Id=sa;Password=Passw0rd
        #    - ASPNETCORE_URLS=http://+:3000 
    db:
        container_name: mssql
        build: 
            context: ./db
            dockerfile: ./Dockerfile
        ports: 
            - "1433:1433"
        restart: always
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "Passw0rd"
            TZ: UTC
        volumes:
            - database-data:/var/opt/mssql
        networks:
            - internalnet    
volumes:
  database-data:
networks: 
    internalnet:

